name: Docker and Semantic Release

on:
  push:
    branches:
      - master

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      contents: write
    outputs:
      published: ${{ steps.release.outputs.published }}
      published_version: ${{ steps.release.outputs.published_version }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Python Semantic Release
        id: release
        uses: relekang/python-semantic-release@master
        with:
          additional_options: --github
          github_token: ${{ secrets.GITHUB_TOKEN }}
    
  docker-release:
    runs-on: ubuntu-latest
    needs: semantic-release
    if: needs.semantic-release.outputs.published == 'True'
    permissions:
      packages: write
    strategy:
      matrix:
        indexer-version: [0.20.8, 0.20.11]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build Docker Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: autoagora-indexer-service
          tags: v${{ needs.semantic-release.outputs.published_version}}-${{ matrix.indexer-version }}
          platforms: linux/amd64
          build-args: |
            INDEXER_SERVICE_TAG=v${{ matrix.indexer-version }}
          containerfiles: |
            ./Dockerfile

      - name: Push
        id: push-to-ghcr
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ghcr.io/${{ github.repository_owner }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Print image url
        run: echo "Image pushed to ${{ steps.push-to-ghcr.outputs.registry-paths }}"