name: Docker and Semantic Release

on:
  push:
    branches:
      - master

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      contents: write
    outputs:
      version: ${{ steps.previoustag.outputs.tag }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Python Semantic Release
        uses: relekang/python-semantic-release@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
    
  docker-release:
    runs-on: ubuntu-latest
    needs: semantic-release
    strategy:
      matrix:
        indexer-version: [0.20.8, 0.20.11, 0.30.0]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/aasseman/autoagora-indexer-service:${{ needs.semantic-release.outputs.version }}-${{ matrix.indexer-version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
